---
- name: install epel repository
  yum:
    name: epel-release
  tags: rkhunter

- name: install rkhunter package
  yum:
    name:
      - rkhunter
      - unhide
      - file
  tags: rkhunter

- name: copy rkhunter conf
  template:
    src: rkhunter.conf.j2
    dest: /etc/rkhunter.conf
    mode: 0640
  notify: update rkhunter database
